name = "gordocrm-api"
main = "src/server.ts"
compatibility_date = "2026-04-04"

[vars]
APP_ENV = "development"
CORS_ORIGIN = "http://localhost:4321"

[assets]
directory = "./portal/dist"

[[d1_databases]]
binding = "DB"
database_name = "gordocrm"
database_id = "557ac4b2-6aa6-4b77-9607-d6b347d54512"
migrations_dir = "db/migrations"

[env.production.vars]
APP_ENV = "production"
CORS_ORIGIN = "https://gordocrm-api-production.alangreydop.workers.dev,https://grandeandgordo.com,https://www.grandeandgordo.com"

[[env.production.d1_databases]]
binding = "DB"
database_name = "gordocrm"
database_id = "557ac4b2-6aa6-4b77-9607-d6b347d54512"
migrations_dir = "db/migrations"
